const modulosComplementaresEscrivao = [
  {
    titulo: "Prática Cartorária e Inquérito Policial",
    pesoEdital: 0.75,
    aulas: [
      {
        titulo: "Estrutura e finalidade do inquérito policial",
        resumo: "Visão prática da natureza, finalidade, características e organização do inquérito policial na rotina da unidade.",
        objetiva: {
          enunciado: "Qual é a finalidade central do inquérito policial?",
          alternativas: [
            "Aplicar diretamente a pena ao investigado",
            "Apurar a materialidade e os indícios de autoria da infração penal",
            "Substituir definitivamente o processo judicial",
            "Produzir apenas estatísticas administrativas",
          ],
          correta: "b",
          justificativa: "O inquérito é um procedimento investigativo destinado a reunir elementos sobre materialidade e autoria; ele não aplica pena nem substitui o processo.",
        },
        discursiva: "Explique a finalidade do inquérito policial e diferencie sua função da atividade jurisdicional.",
      },
      {
        titulo: "Instauração: portaria, flagrante e requisição",
        resumo: "Formas de instauração do inquérito e providências cartorárias iniciais em portaria, auto de prisão em flagrante e requisição.",
        objetiva: {
          enunciado: "Em uma instauração por portaria, qual providência cartorária é essencial?",
          alternativas: [
            "Eliminar o registro de origem da notícia",
            "Autuar a portaria e organizar os documentos que deram origem ao procedimento",
            "Encerrar o procedimento antes das diligências",
            "Remeter os autos sem identificação ou numeração",
          ],
          correta: "b",
          justificativa: "A autuação organiza formalmente o procedimento e preserva a origem e a sequência dos documentos.",
        },
        discursiva: "Descreva as providências iniciais para autuar um inquérito instaurado por portaria.",
      },
      {
        titulo: "Autuação, numeração e organização dos autos",
        resumo: "Técnicas de autuação, ordenação cronológica, numeração, juntada e conferência das peças do procedimento policial.",
        objetiva: {
          enunciado: "A organização cronológica e a numeração dos autos têm como principal objetivo:",
          alternativas: [
            "Dificultar a consulta por terceiros autorizados",
            "Garantir rastreabilidade, integridade e compreensão da sequência dos atos",
            "Dispensar a conferência das peças juntadas",
            "Permitir a retirada de documentos sem registro",
          ],
          correta: "b",
          justificativa: "A correta ordenação torna os atos rastreáveis e protege a integridade documental do procedimento.",
        },
        discursiva: "Monte um checklist de conferência para a juntada de uma nova peça aos autos.",
      },
      {
        titulo: "Termos de declarações, interrogatório e acareações",
        resumo: "Preparação e formalização de termos, qualificação das pessoas ouvidas e registro fiel dos atos de oitiva e acareação.",
        objetiva: {
          enunciado: "Na elaboração de um termo de declarações, deve-se priorizar:",
          alternativas: [
            "A interpretação pessoal do servidor sobre os fatos",
            "O registro claro, fiel e completo do ato, com a correta qualificação dos participantes",
            "A omissão de informações contraditórias",
            "O uso de abreviações não padronizadas",
          ],
          correta: "b",
          justificativa: "O termo deve documentar o ato com clareza e fidelidade, sem substituir o relato por impressões pessoais.",
        },
        discursiva: "Indique os elementos indispensáveis de um termo de declarações bem formalizado.",
      },
      {
        titulo: "Prazos, relatórios, remessa e diligências pendentes",
        resumo: "Controle de prazos, certificação de pendências, preparação dos autos para relatório e remessa e acompanhamento de novas diligências.",
        objetiva: {
          enunciado: "Qual prática reduz o risco de perda de prazo em um cartório policial?",
          alternativas: [
            "Confiar apenas na memória da equipe",
            "Manter controle atualizado de prazos, responsáveis e diligências pendentes",
            "Registrar apenas procedimentos já encerrados",
            "Evitar certificar movimentações nos autos",
          ],
          correta: "b",
          justificativa: "O controle documentado de prazos e pendências permite acompanhamento e responsabilização adequados.",
        },
        discursiva: "Proponha um fluxo de controle para prazos e diligências pendentes de um inquérito.",
      },
      {
        titulo: "Cadeia de custódia documental e de vestígios",
        resumo: "Registros que preservam a história cronológica, a integridade e a rastreabilidade de documentos e vestígios recebidos pela unidade.",
        objetiva: {
          enunciado: "A rastreabilidade na cadeia de custódia permite identificar:",
          alternativas: [
            "Somente o responsável pela apreensão inicial",
            "Cada etapa de reconhecimento, coleta, transporte, recebimento, armazenamento e destinação",
            "Apenas o local final de armazenamento",
            "Exclusivamente a autoridade que concluiu o inquérito",
          ],
          correta: "b",
          justificativa: "A cadeia de custódia documenta a história cronológica do vestígio ao longo de todas as etapas pertinentes.",
        },
        discursiva: "Explique por que a documentação de cada transferência é relevante para a cadeia de custódia.",
      },
    ],
  },
  {
    titulo: "Redação Oficial e Documentação Policial",
    pesoEdital: 0.5,
    aulas: [
      {
        titulo: "Padrão ofício e comunicação oficial",
        resumo: "Princípios de clareza, precisão, concisão, impessoalidade e padronização aplicados à comunicação oficial.",
        objetiva: {
          enunciado: "Qual atributo é incompatível com a redação oficial?",
          alternativas: ["Clareza", "Impessoalidade", "Ambiguidade intencional", "Concisão"],
          correta: "c",
          justificativa: "A comunicação oficial deve ser clara e precisa; ambiguidade compromete a compreensão do ato.",
        },
        discursiva: "Reescreva uma comunicação excessivamente informal segundo os atributos da redação oficial.",
      },
      {
        titulo: "Portarias, despachos, certidões e informações",
        resumo: "Finalidade e estrutura dos principais documentos produzidos na rotina administrativa e cartorária policial.",
        objetiva: {
          enunciado: "A certidão é utilizada, em regra, para:",
          alternativas: [
            "Registrar ou atestar formalmente um fato constante da atividade funcional",
            "Criar uma lei penal",
            "Substituir qualquer decisão da autoridade",
            "Dispensar a identificação de quem a lavrou",
          ],
          correta: "a",
          justificativa: "A certidão formaliza a constatação de um fato ou circunstância no âmbito da atividade funcional.",
        },
        discursiva: "Diferencie, pela finalidade, portaria, despacho e certidão.",
      },
      {
        titulo: "Termos, autos e boletins: clareza e precisão",
        resumo: "Registro objetivo de fatos, pessoas, circunstâncias e providências em termos, autos e boletins.",
        objetiva: {
          enunciado: "Ao registrar um fato em documento policial, a melhor prática é:",
          alternativas: [
            "Misturar fatos observados com opiniões pessoais",
            "Separar fatos, declarações e providências com linguagem objetiva",
            "Suprimir datas e horários para abreviar o texto",
            "Usar termos vagos quando houver informação precisa",
          ],
          correta: "b",
          justificativa: "A separação entre fatos, declarações e providências melhora a precisão e reduz ambiguidades.",
        },
        discursiva: "Crie um roteiro de informações mínimas para o registro objetivo de uma ocorrência.",
      },
      {
        titulo: "Fé pública, autenticidade e responsabilidade funcional",
        resumo: "Responsabilidade pela produção documental, identificação do agente, conferência, assinatura e correção de registros.",
        objetiva: {
          enunciado: "Antes de assinar um documento funcional, o servidor deve:",
          alternativas: [
            "Conferir conteúdo, identificação, datas e anexos pertinentes",
            "Presumir que qualquer rascunho está correto",
            "Remover o histórico de correções",
            "Deixar campos essenciais em branco",
          ],
          correta: "a",
          justificativa: "A conferência protege a autenticidade do documento e reduz erros que afetam o procedimento.",
        },
        discursiva: "Explique a relação entre conferência documental, fé pública e responsabilidade funcional.",
      },
      {
        titulo: "Sigilo, LGPD e proteção de dados na unidade policial",
        resumo: "Tratamento responsável de dados pessoais, controle de acesso, compartilhamento justificado e prevenção de exposição indevida.",
        objetiva: {
          enunciado: "O acesso a dados de um procedimento deve ocorrer:",
          alternativas: [
            "Por curiosidade funcional, mesmo sem relação com o trabalho",
            "Conforme necessidade, autorização e finalidade legítima do serviço",
            "Sempre por conta pessoal de mensagem",
            "Sem registro quando houver informação sensível",
          ],
          correta: "b",
          justificativa: "Necessidade, finalidade e controle de acesso são medidas essenciais de proteção de dados.",
        },
        discursiva: "Apresente quatro cuidados para evitar exposição indevida de dados em uma unidade policial.",
      },
      {
        titulo: "Atendimento ao público e comunicação institucional",
        resumo: "Comunicação respeitosa, acessível e objetiva no atendimento, com preservação de sigilo e encaminhamento adequado.",
        objetiva: {
          enunciado: "Em um atendimento institucional adequado, deve-se:",
          alternativas: [
            "Prometer resultado que não depende do atendente",
            "Explicar o encaminhamento com clareza e preservar informações protegidas",
            "Divulgar detalhes de outros procedimentos",
            "Evitar registrar a demanda recebida",
          ],
          correta: "b",
          justificativa: "Clareza, registro e preservação do sigilo são pilares do atendimento institucional.",
        },
        discursiva: "Descreva como orientar uma pessoa sem divulgar informação sigilosa do procedimento.",
      },
    ],
  },
  {
    titulo: "Arquivologia e Gestão Documental",
    pesoEdital: 0.5,
    aulas: [
      {
        titulo: "Fundamentos de arquivo e ciclo documental",
        resumo: "Conceitos de documento e arquivo e as fases corrente, intermediária e permanente do ciclo documental.",
        objetiva: {
          enunciado: "Documentos frequentemente consultados pela unidade pertencem, em regra, ao arquivo:",
          alternativas: ["Corrente", "Intermediário", "Permanente", "Eliminado"],
          correta: "a",
          justificativa: "O arquivo corrente reúne documentos em uso frequente e necessários às atividades em andamento.",
        },
        discursiva: "Diferencie as fases corrente, intermediária e permanente do ciclo documental.",
      },
      {
        titulo: "Classificação, avaliação e temporalidade",
        resumo: "Organização por plano de classificação, avaliação de valores documentais e aplicação de tabela de temporalidade.",
        objetiva: {
          enunciado: "A tabela de temporalidade serve para:",
          alternativas: [
            "Definir prazos de guarda e destinação dos documentos",
            "Substituir o protocolo de recebimento",
            "Autorizar a eliminação imediata de qualquer documento",
            "Ordenar documentos apenas por tamanho",
          ],
          correta: "a",
          justificativa: "A tabela orienta os prazos de guarda e a destinação, observados os requisitos de avaliação documental.",
        },
        discursiva: "Explique como classificação, avaliação e temporalidade se relacionam.",
      },
      {
        titulo: "Protocolo, tramitação e controle de documentos",
        resumo: "Recebimento, registro, distribuição, movimentação e expedição com rastreabilidade dos documentos.",
        objetiva: {
          enunciado: "Qual informação é indispensável no controle de tramitação?",
          alternativas: [
            "Apenas a cor da pasta",
            "Origem, destino, data e responsável pela movimentação",
            "Somente o assunto abreviado",
            "A opinião do responsável sobre o conteúdo",
          ],
          correta: "b",
          justificativa: "Esses dados permitem localizar o documento e reconstruir seu fluxo de movimentação.",
        },
        discursiva: "Desenhe um fluxo básico de protocolo desde o recebimento até a expedição.",
      },
      {
        titulo: "Arquivamento físico, digitalização e preservação",
        resumo: "Métodos de arquivamento, preparação para digitalização, controle de qualidade e preservação de documentos físicos e digitais.",
        objetiva: {
          enunciado: "A digitalização de um documento dispensa automaticamente a guarda do original?",
          alternativas: [
            "Sim, em qualquer situação",
            "Não; a destinação deve observar requisitos legais e a política de gestão documental",
            "Sim, desde que o arquivo tenha nome curto",
            "Não, porque documentos nunca podem ser eliminados",
          ],
          correta: "b",
          justificativa: "A eliminação ou preservação depende das normas aplicáveis e da avaliação documental, não apenas da digitalização.",
        },
        discursiva: "Liste controles de qualidade necessários em um processo de digitalização.",
      },
      {
        titulo: "Gestão eletrônica de documentos e segurança da informação",
        resumo: "Metadados, perfis de acesso, versões, cópias de segurança e trilhas de auditoria em sistemas documentais.",
        objetiva: {
          enunciado: "Uma trilha de auditoria em sistema documental permite:",
          alternativas: [
            "Apagar alterações sem registro",
            "Identificar acessos e operações relevantes realizados no documento",
            "Compartilhar senhas entre usuários",
            "Dispensar cópias de segurança",
          ],
          correta: "b",
          justificativa: "A trilha de auditoria registra eventos relevantes e apoia controle, responsabilização e investigação de incidentes.",
        },
        discursiva: "Explique a função de metadados, perfis de acesso e trilhas de auditoria.",
      },
      {
        titulo: "Localização, desarquivamento e destinação",
        resumo: "Instrumentos de busca, registro de retirada, retorno ao arquivo e destinação segura segundo a temporalidade.",
        objetiva: {
          enunciado: "Ao desarquivar um documento, deve-se:",
          alternativas: [
            "Retirá-lo sem deixar referência",
            "Registrar retirada, responsável, finalidade e devolução",
            "Alterar sua classificação original sem justificativa",
            "Descartar o instrumento de busca",
          ],
          correta: "b",
          justificativa: "O registro da retirada preserva a localização e a responsabilidade sobre o documento.",
        },
        discursiva: "Proponha um controle simples para retirada e devolução de documentos arquivados.",
      },
    ],
  },
];

const flashcardsPoliciaCivil = [
  ["Língua Portuguesa", null, "O que caracteriza a coesão textual?", "O uso de mecanismos linguísticos que conectam palavras, orações e parágrafos, como referências, conectivos e substituições."],
  ["Língua Portuguesa", null, "Qual é a diferença entre coesão e coerência?", "Coesão é a ligação linguística entre partes do texto; coerência é a unidade de sentido e a compatibilidade lógica das ideias."],
  ["Língua Portuguesa", null, "Quando ocorre crase?", "Em regra, quando há fusão da preposição a com o artigo feminino a/as ou com o a inicial de certos pronomes demonstrativos."],
  ["Língua Portuguesa", null, "Qual é a regra geral da concordância verbal?", "O verbo concorda em número e pessoa com o núcleo do sujeito, ressalvadas as construções especiais."],
  ["Raciocínio Lógico-Matemático", null, "Qual é a negação de “Todo A é B”?", "Existe pelo menos um A que não é B."],
  ["Raciocínio Lógico-Matemático", null, "Quando a implicação P → Q é falsa?", "Somente quando P é verdadeira e Q é falsa."],
  ["Raciocínio Lógico-Matemático", null, "Como calcular um aumento de p% sobre um valor V?", "Multiplique V por 1 + p/100."],
  ["Noções de Informática", null, "O que a autenticação em dois fatores acrescenta à senha?", "Um segundo fator independente, reduzindo o risco de acesso mesmo quando a senha é descoberta."],
  ["Noções de Informática", null, "Qual é a função de um backup?", "Manter cópia recuperável dos dados para restaurá-los após perda, corrupção ou incidente."],
  ["Noções de Informática", null, "O que é phishing?", "Tentativa de enganar a vítima para obter dados ou induzir uma ação, normalmente por mensagens ou páginas que imitam fontes legítimas."],
  ["Noções de Informática", null, "Qual é a diferença básica entre memória RAM e armazenamento?", "RAM mantém temporariamente dados em uso; armazenamento preserva dados de forma não volátil."],
  ["Noções de Administração", null, "Quais são as quatro funções clássicas da administração?", "Planejar, organizar, dirigir e controlar."],
  ["Noções de Administração", null, "O que é eficiência?", "Uso adequado dos recursos e dos meios para realizar uma atividade com menor desperdício."],
  ["Noções de Administração", null, "O que é eficácia?", "Alcance dos objetivos e resultados pretendidos."],
  ["Noções de Contabilidade", null, "Qual é a equação patrimonial básica?", "Ativo = Passivo + Patrimônio Líquido."],
  ["Noções de Contabilidade", null, "O que é ativo?", "Conjunto de recursos controlados pela entidade dos quais se esperam benefícios econômicos."],
  ["Noções de Contabilidade", null, "O que é passivo?", "Obrigação presente da entidade cuja liquidação deve provocar saída de recursos."],
  ["Noções de Contabilidade", null, "Qual é a finalidade do balanço patrimonial?", "Evidenciar a posição patrimonial e financeira da entidade em determinada data."],
  ["Direito Constitucional", null, "O que distingue direitos fundamentais de garantias fundamentais?", "Direitos são bens e posições protegidas; garantias são instrumentos destinados a assegurar sua proteção e exercício."],
  ["Direito Constitucional", null, "Qual é a função do habeas corpus?", "Proteger a liberdade de locomoção contra ilegalidade ou abuso de poder."],
  ["Direito Constitucional", null, "Quais são os princípios expressos do art. 37 da Constituição?", "Legalidade, impessoalidade, moralidade, publicidade e eficiência."],
  ["Direito Constitucional", null, "O que é controle de constitucionalidade?", "Verificação da compatibilidade de leis e atos normativos com a Constituição."],
  ["Direito Penal", null, "Quais são os elementos do fato típico na estrutura analítica usual?", "Conduta, resultado quando exigido, nexo causal e tipicidade."],
  ["Direito Penal", null, "Qual é a diferença entre dolo e culpa?", "No dolo o agente quer o resultado ou assume o risco; na culpa viola o dever de cuidado sem querer o resultado."],
  ["Direito Penal", null, "Quando há tentativa?", "Quando, iniciada a execução, o crime não se consuma por circunstâncias alheias à vontade do agente."],
  ["Direito Penal", null, "O que é erro de tipo essencial?", "Erro sobre elemento constitutivo do tipo penal, que exclui o dolo e pode permitir punição por culpa se prevista."],
  ["Direito Processual Penal", null, "Qual é a finalidade do inquérito policial?", "Reunir elementos informativos sobre a materialidade e os indícios de autoria de uma infração penal."],
  ["Direito Processual Penal", null, "O inquérito policial é indispensável à ação penal?", "Não. Havendo elementos suficientes por outras fontes, a ação pode ser proposta sem inquérito."],
  ["Direito Processual Penal", null, "O que é ação penal pública incondicionada?", "Ação promovida pelo Ministério Público sem depender de representação da vítima ou requisição, salvo exceções legais."],
  ["Direito Processual Penal", null, "Qual é a finalidade da cadeia de custódia?", "Documentar e preservar a história cronológica e a integridade do vestígio desde o reconhecimento até a destinação."],
  ["Legislação Penal e Processual Penal Extravagante", null, "O que torna uma lei penal “extravagante”?", "Ela disciplina matéria penal ou processual penal fora dos respectivos códigos."],
  ["Legislação Penal e Processual Penal Extravagante", null, "Por que a leitura da lei seca é importante em legislação especial?", "Porque muitas questões cobram requisitos, conceitos, prazos e exceções com redação próxima do texto legal."],
  ["Legislação Penal e Processual Penal Extravagante", null, "Como revisar leis especiais com segurança?", "Separando âmbito de aplicação, sujeitos, condutas, requisitos, procedimentos e exceções, sempre conferindo a versão legal vigente."],
  ["Direito Administrativo", null, "Quais são os elementos do ato administrativo?", "Competência, finalidade, forma, motivo e objeto."],
  ["Direito Administrativo", null, "Qual é a diferença entre anulação e revogação?", "Anulação retira ato ilegal; revogação retira ato válido por conveniência e oportunidade, dentro dos limites legais."],
  ["Direito Administrativo", null, "O que é poder de polícia?", "Atividade estatal que condiciona ou restringe direitos, bens e atividades em benefício do interesse coletivo, nos limites da lei."],
  ["Direito Administrativo", null, "O que é responsabilidade civil objetiva do Estado?", "Dever de reparar dano causado por agente público nessa qualidade, independentemente de provar culpa estatal, sem excluir excludentes aplicáveis."],
  ["Medicina Legal", null, "O que estuda a traumatologia forense?", "As lesões e energias causadoras de dano relevantes para a investigação e a aplicação do direito."],
  ["Medicina Legal", null, "Qual é a diferença entre causa, mecanismo e natureza jurídica da morte?", "Causa é a lesão ou doença determinante; mecanismo é a alteração fisiopatológica; natureza jurídica classifica a morte, por exemplo, como natural, acidental, suicida ou homicida."],
  ["Medicina Legal", null, "O que é identidade médico-legal?", "Conjunto de características usadas para estabelecer ou confirmar a individualidade de uma pessoa."],
  ["Prática Cartorária e Inquérito Policial", "escrivao", "Qual é a finalidade da autuação?", "Dar forma e organização inicial ao procedimento, reunindo a peça inaugural e os documentos relacionados em autos identificados e ordenados."],
  ["Prática Cartorária e Inquérito Policial", "escrivao", "O que deve constar no controle de uma diligência pendente?", "A diligência, o responsável, a data de solicitação, o prazo, o estado atual e o resultado ou motivo da pendência."],
  ["Prática Cartorária e Inquérito Policial", "escrivao", "Por que numerar e ordenar as peças dos autos?", "Para preservar integridade, rastreabilidade e compreensão da sequência dos atos."],
  ["Prática Cartorária e Inquérito Policial", "escrivao", "Qual é a regra de ouro ao redigir um termo de declarações?", "Registrar de forma clara e fiel o ato e identificar corretamente os participantes, sem inserir opinião pessoal como se fosse relato."],
  ["Prática Cartorária e Inquérito Policial", "escrivao", "O que a cadeia de custódia documenta?", "A história cronológica do vestígio, com registro das etapas e dos responsáveis por seu manuseio e guarda."],
  ["Prática Cartorária e Inquérito Policial", "escrivao", "Como a conclusão de um módulo comum é aproveitada entre Agente e Escrivão?", "A mesma aula possui um único registro de progresso por usuário; ao aparecer nas duas trilhas, sua conclusão e XP não são duplicados."],
  ["Redação Oficial e Documentação Policial", "escrivao", "Quais atributos devem orientar a redação oficial?", "Clareza, precisão, objetividade, concisão, impessoalidade, formalidade e padronização."],
  ["Redação Oficial e Documentação Policial", "escrivao", "Para que serve uma certidão?", "Para registrar ou atestar formalmente um fato ou circunstância verificada no exercício da função."],
  ["Redação Oficial e Documentação Policial", "escrivao", "O que deve ser separado em um registro policial?", "Fatos observados, declarações das pessoas e providências adotadas, evitando confundir relato com opinião."],
  ["Redação Oficial e Documentação Policial", "escrivao", "Qual cuidado antecede a assinatura de um documento funcional?", "Conferir conteúdo, identificação, datas, referências, anexos e competência de quem assina."],
  ["Redação Oficial e Documentação Policial", "escrivao", "Como tratar dados pessoais em uma unidade policial?", "Com finalidade legítima, necessidade, controle de acesso, segurança e respeito ao sigilo e às normas aplicáveis."],
  ["Redação Oficial e Documentação Policial", "escrivao", "Como orientar o público sem violar sigilo?", "Explicar procedimentos e encaminhamentos permitidos, sem revelar dados protegidos de pessoas ou investigações."],
  ["Arquivologia e Gestão Documental", "escrivao", "Quais são as três fases do ciclo documental?", "Corrente, intermediária e permanente."],
  ["Arquivologia e Gestão Documental", "escrivao", "Para que serve a tabela de temporalidade?", "Para definir prazos de guarda, transferência, recolhimento e destinação dos documentos."],
  ["Arquivologia e Gestão Documental", "escrivao", "Quais dados tornam a tramitação rastreável?", "Origem, destino, data, responsável e identificação do documento ou processo."],
  ["Arquivologia e Gestão Documental", "escrivao", "Digitalizar autoriza eliminar imediatamente o original?", "Não. A destinação depende das normas aplicáveis, da avaliação documental e dos requisitos de autenticidade e preservação."],
  ["Arquivologia e Gestão Documental", "escrivao", "Para que serve uma trilha de auditoria?", "Para registrar acessos e operações relevantes, apoiando rastreabilidade, controle e responsabilização."],
  ["Arquivologia e Gestão Documental", "escrivao", "O que registrar ao desarquivar um documento?", "Documento retirado, responsável, data, finalidade, destino e devolução."],
  ["Direito Financeiro e Tributário", "delegado", "Qual é a função do orçamento público?", "Planejar e autorizar receitas e despesas públicas para determinado período, observadas as regras constitucionais e legais."],
  ["Direito Financeiro e Tributário", "delegado", "O que é tributo?", "Prestação pecuniária compulsória instituída em lei, que não constitui sanção de ato ilícito e é cobrada mediante atividade administrativa vinculada."],
  ["Direito Ambiental", "delegado", "O que é responsabilidade ambiental em três esferas?", "Uma mesma conduta pode gerar, de forma independente, consequências civis, administrativas e penais."],
  ["Direito Ambiental", "delegado", "Qual é a ideia central do princípio da prevenção?", "Agir antes do dano quando os riscos ambientais são conhecidos, adotando medidas para evitá-lo ou reduzi-lo."],
  ["Criminalística", "delegado", "Qual é o objeto da criminalística?", "O exame técnico-científico de vestígios materiais relacionados a uma infração, auxiliando a reconstrução dos fatos."],
  ["Criminalística", "delegado", "Por que preservar o local de crime?", "Para evitar alteração, perda ou contaminação de vestígios relevantes ao exame pericial."],
  ["Criminologia", "delegado", "Qual é a diferença entre criminologia e direito penal?", "A criminologia estuda empiricamente crime, autor, vítima e controle social; o direito penal define juridicamente crimes e sanções."],
  ["Criminologia", "delegado", "O que é prevenção terciária do delito?", "Medidas dirigidas a pessoas que já cometeram infrações, buscando reduzir reincidência e favorecer reintegração."],
].map(([moduloTitulo, trilhaSlug, frente, verso], indice) => ({
  moduloTitulo,
  trilhaSlug,
  frente,
  verso,
  chaveOrigem: `catalogo-policia-civil:${trilhaSlug || "comum"}:${String(indice + 1).padStart(3, "0")}`,
}));

module.exports = { modulosComplementaresEscrivao, flashcardsPoliciaCivil };
